# Quandl tutorial

<b>verze ntb:</b> 0.0.2

<b>datum poslední úpravy:</b> 27.5.2016

## Další použité packages

<b>quandl:</b> 3.0.0

## Co to je Quandl
Quandl z quandl.com je API, které poskytuje přístup k datám na burze. Quandl obsahuje ticková data akcií, které jsou obsaženy v S&P 500, NASDAQ 100 a Dow Jones 30.

<i>Otázky k vyřešení:</i>
* Nenašel jsem na quandlu intradenní data jednotlivých Indexů, budu to řešit pomocí exportu ze Sierra Chart nebo metatraderu.

### Instalace
V příkazové řádce anaconda spustit příkaz:

pip install quandl

In [42]:
import quandl as q
q.ApiConfig.api_key = open('../etc/quandl-token.key','r').read() # authorize Quandl

## Futures data
### Currencies
ICE US Dollar Index Futures (DX): https://www.quandl.com/collections/futures/ice-us-dollar-index-futures

CME Euro FX Futures (EC): https://www.quandl.com/collections/futures/cme-euro-fx-futures

CME British Pound GBP (BP): https://www.quandl.com/collections/futures/cme-british-pound-futures

CME Australian Dollar (AD): https://www.quandl.com/collections/futures/cme-australian-dollar-futures

CME Japanese Yen JPY Futures (JY): https://www.quandl.com/collections/futures/cme-japanese-yen-futures

CME New Zealand Dollar NZD Futures (NE): https://www.quandl.com/collections/futures/cme-new-zealand-dollar-futures

CME Canadian Dollar CAD Futures (CD): https://www.quandl.com/collections/futures/cme-canadian-dollar-futures

### Indexes US
CME S&P 500 Index E-Mini Futures (ES): https://www.quandl.com/collections/futures/cme-e-mini-s-and-p-500-index-futures

S%P 500 Intraday - M1: https://www.quandl.com/data/AS500

CME NASDAQ 100 Index E-Mini Futures (NQ) https://www.quandl.com/collections/futures/cme-e-mini-nasdaq-100-index-futures

CME E-mini Dow Jones Futures (YM): https://www.quandl.com/collections/futures/cme-e-mini-dow-jones-futures

### Indexes EU
EUREX DAX Futures (FDAX): https://www.quandl.com/collections/futures/eurex-dax-futures

LIFFE FTSE 100 Index Futures (Z): https://www.quandl.com/collections/futures/liffe-ftse-100-index-futures

EUREX EURO STOXX 50 Index Futures (FESX): https://www.quandl.com/collections/futures/eurex-euro-stoxx-50-index-futures

### Indexes Other
CME Nikkei 225 Futures (NK): https://www.quandl.com/collections/futures/cme-nikkei-225-index-futures

Hong Kong Hang Seng Index Futures (HSI): https://www.quandl.com/collections/futures/hkex-hang-seng-index-futures

## Curencies data
There are data about all exchange related to one currency.

Exchange Rates versus EUR: https://www.quandl.com/collections/markets/exchange-rates-versus-eur

Exchange Rates versus AUD: https://www.quandl.com/collections/markets/exchange-rates-versus-aud

Exchange Rates versus USD: https://www.quandl.com/collections/usa/usa-currency-exchange-rate

G-10 Cross Rates (USD, JPY, EUR, GBP, CHF, CAD, AUD, NZD, SEK, NOK): https://www.quandl.com/collections/markets/g-10-cross-rates

## Get data

DAX futures (last month) - dayly

In [45]:
dax_data=q.get("CHRIS/EUREX_FDAX1") # get all dayly data of DAX
dax_data=q.get("CHRIS/EUREX_FDAX1", limit=3) # get dayly data of DAX futures
dax_data=q.get("CHRIS/EUREX_FDAX1", start_date='2016-04-20', end_date='2016-04-23') # get dayly data of DAX futures
dax_data

,Open,High,Low,Settle,Volume,Prev. Day Open Interest
Date,,,,,,
2016-04-20,10342.0,10495.0,10313.5,10473.5,104874.0,117017.0
2016-04-21,10495.5,10522.0,10371.0,10485.0,108190.0,116246.0
2016-04-22,10428.0,10462.0,10357.0,10396.5,91755.0,117456.0

## Save data to file

In [46]:
dax_data.to_csv("../data/dax_futures_dayly.csv")

## Load data from file

In [49]:
import pandas as pd
pd.read_csv("../data/dax_futures_dayly.csv")

,Date,Open,High,Low,Settle,Volume,Prev. Day Open Interest
0,2016-04-20,10342.0,10495.0,10313.5,10473.5,104874.0,117017.0
1,2016-04-21,10495.5,10522.0,10371.0,10485.0,108190.0,116246.0
2,2016-04-22,10428.0,10462.0,10357.0,10396.5,91755.0,117456.0

              Open    High     Low  Settle   Volume  Prev. Day Open Interest
Date
1996-12-20  2883.0  2886.0  2851.0  2853.0  42539.0                 167561.0
1996-12-23  2861.0  2869.5  2860.0  2865.0   8185.0                 157361.0
1996-12-27  2874.5  2882.0  2872.0  2881.0  10719.0                 161670.0
1996-12-30  2891.0  2909.0  2878.5  2904.5  20063.0                 161670.0
1997-01-02  2840.0  2868.0  2829.0  2835.5  38785.0                 173800.0

In [31]:
q.get('databases')

SyntaxError: Invalid format used for Quandl database code.         The correct format is: `DATABASE_CODE/DATASET_CODE` (<string>)

In [36]:
q.get_table('ZACKS/FC', ticker='AAPL')

,m_ticker,ticker,comp_name,comp_name_2,exchange,currency_code,per_end_date,per_type,per_code,per_fisc_year,...,stock_based_compsn_qd,cash_flow_oper_activity_qd,net_change_prop_plant_equip_qd,comm_stock_div_paid_qd,pref_stock_div_paid_qd,tot_comm_pref_stock_div_qd,wavg_shares_out,wavg_shares_out_diluted,eps_basic_net,eps_diluted_net
None,,,,,,,,,,,,,,,,,,,,,
0,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2011-09-30,A,FR-4,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,6469.806,6556.515,4.0071,3.9543
1,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2012-09-30,A,FR-3,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,6543.726,6617.483,6.3800,6.3100
2,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2013-09-30,A,FR-2,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,6477.320,6521.634,5.7200,5.6800
3,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2014-09-30,A,FR-1,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,6085.572,6122.663,6.4900,6.4500
4,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2015-09-30,A,FR0,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,5753.421,5793.069,9.2800,9.2200
5,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2011-03-31,Q,QR-20,2011,...,287.0,6219.0,-624.0,NaN,NaN,NaN,6462.372,6551.608,0.9271,0.9143
6,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2011-06-30,Q,QR-19,2011,...,284.0,11108.0,-777.0,NaN,NaN,NaN,6482.756,6564.670,1.1271,1.1129
7,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2011-09-30,Q,QR-18,2011,...,298.0,10429.0,-1645.0,NaN,NaN,NaN,6469.806,6556.515,1.0200,1.0086
8,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2011-12-31,Q,QR-17,2012,...,420.0,17554.0,-1321.0,0.0,NaN,NaN,6517.287,6591.004,2.0043,1.9814
9,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2012-03-31,Q,QR-16,2012,...,424.0,13977.0,-1457.0,0.0,NaN,NaN,6535.074,6614.251,1.7786,1.7571
10,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2012-06-30,Q,QR-15,2012,...,448.0,10189.0,-2056.0,0.0,NaN,NaN,6556.172,6629.413,1.3457,1.3314
11,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2012-09-30,Q,QR-14,2012,...,448.0,9136.0,-3461.0,-2488.0,NaN,NaN,6543.726,6617.483,1.2514,1.2400
12,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2012-12-31,Q,QR-13,2013,...,545.0,23426.0,-2317.0,-2493.0,NaN,-2493.0,6572.412,6630.519,1.9900,1.9729
13,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2013-03-31,Q,QR-12,2013,...,575.0,12504.0,-2008.0,-2491.0,NaN,-2491.0,6577.403,6622.245,1.4514,1.4414
14,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2013-06-30,Q,QR-11,2013,...,578.0,7828.0,-1885.0,-2811.0,NaN,-2811.0,6430.323,6469.854,1.0700,1.0700
15,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2013-09-30,Q,QR-10,2013,...,555.0,9908.0,-1955.0,-2769.0,NaN,-2769.0,6477.320,6521.634,1.2086,1.1957
16,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2013-12-31,Q,QR-9,2014,...,681.0,22670.0,-1985.0,-2769.0,NaN,-2769.0,6272.504,6310.161,2.0800,2.0700
17,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2014-03-31,Q,QR-8,2014,...,696.0,13538.0,-1382.0,-2661.0,NaN,-2661.0,6123.302,6156.699,1.6700,1.6600
18,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2014-06-30,Q,QR-7,2014,...,724.0,10255.0,-2378.0,-2867.0,NaN,-2867.0,6012.635,6051.711,1.2900,1.2800
19,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2014-09-30,Q,QR-6,2014,...,762.0,13250.0,-3826.0,-2829.0,NaN,-2829.0,6085.572,6122.663,1.4500,1.4400
20,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2014-12-31,Q,QR-5,2015,...,888.0,33722.0,-3217.0,-2801.0,NaN,-2801.0,5843.082,5881.803,3.0800,3.0600
21,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2015-03-31,Q,QR-4,2015,...,927.0,19081.0,-2369.0,-2743.0,NaN,-2743.0,5793.799,5834.858,2.3400,2.3300
22,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2015-06-30,Q,QR-3,2015,...,856.0,14988.0,-2043.0,-3053.0,NaN,-3053.0,5729.886,5773.099,1.8600,1.8500
23,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2015-09-30,Q,QR-2,2015,...,915.0,13475.0,-3618.0,-2964.0,NaN,-2964.0,5753.421,5793.069,2.0000,1.9800
24,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2015-12-31,Q,QR-1,2016,...,1078.0,27463.0,-3612.0,-2969.0,NaN,-2969.0,5558.930,5594.127,3.3000,3.2800
25,AAPL,AAPL,APPLE INC,Apple Inc.,NSDQ,USD,2016-03-31,Q,QR0,2016,...,1048.0,11601.0,-2336.0,-2902.0,NaN,-2902.0,5514.381,5540.886,1.9100,1.9000